# 1-D ARRAY

In [1]:
from array import *

arr1 = array('i',[1,2,3,4,5,6])
arr2 = array('d',[1.1,2.1,3.1,4.1,5.1])

print(arr1)
print(arr2)

array('i', [1, 2, 3, 4, 5, 6])
array('d', [1.1, 2.1, 3.1, 4.1, 5.1])


In [6]:
# Insertion
arr = array('i',[1,2,3])
# begining
arr.insert(0,9)
print(arr)
# ending
arr.insert(4,10)
print(arr)
# middle
arr.insert(3,7)
print(arr)

array('i', [9, 1, 2, 3])
array('i', [9, 1, 2, 3, 10])
array('i', [9, 1, 2, 7, 3, 10])


In [7]:
# Traversal
def traverseArray(array):
    for i in array:
        print(i)
traverseArray(arr)

9
1
2
7
3
10


In [12]:
# Access the element of array
def accessElement(array, index):
    if index > len(array):
        print("out of length")
    else:
        print(array[index])

i = int(input())
accessElement(arr,i)

8
out of length


In [24]:
from array import *
def searchInArray(array, value):
    for i in array:
        if i == value:
            return array.index(value)
    return "not exist"
    
arr = array('i',[1,2,3])
v = int(input())
searchInArray(arr, v)

1


0

In [5]:
# DELETE AN ARRAY
from array import*
arr = array('i',[1,2,3])
arr.remove(2)
print(arr)

array('i', [1, 3])


# 2-D ARRAY

In [7]:
import numpy as np

In [9]:
# Day 1 - 11, 15, 10, 6
# Day 2 - 10, 14, 11, 5
# Day 3 - 12, 17, 12, 8
# Day 4 - 15, 18, 14, 9
twoDarr = np.array([[11, 15, 10, 6],[10, 14, 11, 5],[12, 17, 12, 8],[15, 18, 14, 9]])
print(twoDarr)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [11]:
# Insertion
# column
newTwoDarr = np.insert(twoDarr, 0,[[1, 2, 3, 4]], axis=1)
print(newTwoDarr)

[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]


In [15]:
# Insertion
# column
newTwoDarr2 = np.insert(twoDarr, 2,[[10, 5, 6, 78]], axis=0)
print(newTwoDarr2)

[[11 15 10  6]
 [10 14 11  5]
 [10  5  6 78]
 [12 17 12  8]
 [15 18 14  9]]


In [17]:
# access the elements of 2-D array
def accessTwoDarr(array, rowIndex, colIndex):
    if rowIndex > len(array) or colIndex >len(array[0]):#------------------------> O(1)
        print("out of length")#---------------------------------------------------> O(1)
    else:
        print(array[rowIndex][colIndex])#-----------------------------------------> O(1)

arr = np.array([[11, 15, 10, 6],[10, 14, 11, 5],[12, 17, 12, 8],[15, 18, 14, 9]])
rownum = int(input("Enter the row number: "))
colnum = int(input("Enter the column number: "))
print(arr)
accessTwoDarr(arr, rownum, colnum)

Enter the row number: 3
Enter the column number: 2
[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
14


In [20]:
# Traverse in 2-D array
def traverseTDA(array):
    for i in range(len(array)):#------------>O(m)---
                                                #   -------------->O(n^2)
        for j in range(len(array[0])):#----->O(n)---
            print(array[i][j])

print(arr)
traverseTDA(arr)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [24]:
def searchEleTDA(array, element):
    for i in range(len(array)): #--------------------------------------------->O(n)
                                                                            #      ------>O(n^2)
        for j in range(len(array[0])):#--------------------------------------->O(n)
            if element == array[i][j]:#--------------------------------------->O(1)
                print("The value is located in index a[",i,"][",j,"]")#------->O(1)
            else:
                pass
    print("These element is not exist in 2-D array.")#------------------------>O(1)

print(arr)
searchEleTDA(arr, 14)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
The value is located in index a[ 1 ][ 1 ]
The value is located in index a[ 3 ][ 2 ]
These element is not exist in 2-D array.


In [27]:
# Delete
print(arr,"\n")
newarr = np.delete(arr, 0, axis=0)
print(newarr)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]] 

[[10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
